### ISSUE TITLE
Complete UI rewrite

### ISSUE THREAD

**Issue by jatindhankhar** [quiksort/quiksort.github.io#6]
Do a complete re-write of QuikSort's site

**Comment by bitsch** [comment]
Is open theme is the site u wanted

**Comment by jatindhankhar** [comment]
Opentheme will be the new theming template.
Sort of but customized. Will we use this for few days until we make one of our own. Check the semantic ui stuff, it's pretty awesome

**Comment by bitsch** [comment]
currently i am working on the college website

**Comment by jatindhankhar** [comment]
You can shift the development to the quiksort repos so that interested members can participate. :+1:

**Comment by bitsch** [comment]
YOU want to participate??

**Comment by jatindhankhar** [comment]
Sure :8ball:

**Comment by bitsch** [comment]
oh ill shift it there

**Comment by bitsch** [comment]
it says i dont have admin rights of quiksort!!
if u wish i can add u as collaborator

**Comment by jatindhankhar** [comment]
Latest push
 Commit 5ee591ce488703622f8a0a60732a58411d822f4b fixes this
